/* NTT backend for q=3329, n=256, R=X^256+1 (7-layer DIT, verified schedule).
 * Tables: c/ntt_tables.h (generated by ref/ntt_gen.py).
 * Valid ONLY for q==3329 && n==256; all entry points fall back to schoolbook
 * otherwise (toy params unaffected). Reductions via Barrett (q=3329).
 * NOT yet constant-time (data-dependent % in butterfly adjusts) -- see docs.
 */
#ifndef RMDQ_NTT_H
#define RMDQ_NTT_H

#include "rmdq.h"

/* out = a*b mod (X^256+1), q must be 3329 (else falls back to schoolbook). */
void rmdq_poly_mul_ntt(const int *a, const int *b, int *out, int n, int q);
/* forward/inverse exposed for tests (n must be 256, q 3329). */
void rmdq_ntt_fwd(int *a);
void rmdq_ntt_inv(int *a);
/* Constant-time shape twins: identical outputs, no data-dependent branches
 * (masked arithmetic; arithmetic >>31 assumed, verified by equivalence tests
 * + objdump smoke check in docs). */
void rmdq_ntt_fwd_ct(int *a);
void rmdq_ntt_inv_ct(int *a);
void rmdq_poly_mul_ntt_ct(const int *a, const int *b, int *out, int n, int q);
#ifndef RMDQ_NTT
#define RMDQ_NTT rmdq_poly_mul_ntt
#endif
#ifndef RMDQ_MATVEC_NTT
#define RMDQ_MATVEC_NTT rmdq_mat_vec_mul_ntt
#endif
void rmdq_mat_vec_mul_ntt_ct(const int *A, const int *s, int *out, const rmdq_params *p);
/* Precomputed-Ahat variant: Ahat = NTT(A) entrywise (use rmdq_ntt_batch_fwd
 * below, or transform manually); skips k*k forward transforms per call.
 * Falls back to streaming schoolbook unless q==3329 && n==256. */
void rmdq_mat_vec_mul_ahat(const int *Ahat, const int *s, int *out, const rmdq_params *p);
void rmdq_ntt_batch_fwd(int *a, int count);/* k x k mat-vec via NTT (q==3329, n==256 only; falls back otherwise). */
void rmdq_mat_vec_mul_ntt(const int *A, const int *s, int *out, const rmdq_params *p);

#endif
